# PersonaChain Node 4 Configuration
minimum-gas-prices = "0persona"

[api]
enable = true
swagger = true
address = "tcp://localhost:1314"
max-open-connections = 1000
rpc-read-timeout = 10
rpc-write-timeout = 0
rpc-max-body-bytes = 1000000
enabled-unsafe-cors = true

[grpc]
enable = true
address = "localhost:9084"

[state-sync]
snapshot-interval = 0
snapshot-keep-recent = 2
