modules:
  - name: runtime
    config:
      "@type": cosmos.app.runtime.v1alpha1.Module
      app_name: PersonaChain
      
      begin_blockers: [upgrade, staking]
      end_blockers: [staking]
      init_genesis: [auth, bank, staking, genutil, upgrade, consensus]
      export_genesis: [consensus, upgrade, staking, bank, auth, genutil]
      
      override_store_keys:
        - module_name: auth
          kv_store_key: acc
      
  - name: auth
    config:
      "@type": cosmos.auth.module.v1.Module
      bech32_prefix: persona
      module_account_permissions:
        - account: fee_collector
        - account: bonded_tokens_pool
          permissions: [burner, staking]
        - account: not_bonded_tokens_pool
          permissions: [burner, staking]
      authority: cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn

  - name: bank
    config:
      "@type": cosmos.bank.module.v1.Module
      blocked_module_accounts_override: [fee_collector, bonded_tokens_pool, not_bonded_tokens_pool]
      authority: cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn

  - name: staking
    config:
      "@type": cosmos.staking.module.v1.Module
      authority: cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn

  - name: genutil
    config:
      "@type": cosmos.genutil.module.v1.Module

  - name: upgrade
    config:
      "@type": cosmos.upgrade.module.v1.Module
      authority: cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn

  - name: consensus
    config:
      "@type": cosmos.consensus.module.v1.Module
      authority: cosmos10d07y265gmmuvt4z0w9aw880jnsr700j6zn9kn

